### ISSUE TITLE
Lazy-load error when using ggplot2

### ISSUE THREAD

**Issue by auskate** [bnicenboim/eeguana#1]
I'm getting some of these errors in when plotting. Everything works, it just pops up while I'm typing:

Error in fetch(key) :
  lazy-load database '/home/stoner/R/x86_64-pc-linux-gnu-library/3.4/ggplot2/help/ggplot2.rdb' is corrupt

According to these, it's a problem at my end, but maybe it can be helped at the package end?:
https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database
https://github.com/r-lib/devtools/pull/1001

**Comment by bnicenboim** [comment]
I don't think I can do anything on my end. Closing for now.
