### ISSUE TITLE
import BDF

### ISSUE THREAD

**Issue by livioivil** [bnicenboim/eeguana#121]
Hi notice an issue while importing a bdf file.
My example:
http://headit.ucsd.edu/recording_sessions/33a6adea-35ff-11e3-a2a9-0050563f2612
I downloaded: eeg_recording_1.bdf

When I tried to import with eeguana all was fine, but **the events table is empty**

Deg=eeguana::read_edf("eeg_recording_1.bdf")
pryr::object_size(Deg)
str(Deg)

While when I try with eegUtils it imported it well:

D0=eegUtils::import_raw("eeg_recording_1.bdf")
table(D0$ events$event_type)
length(D0$ events$event_type)
pryr::object_size(D0)

**Comment by bnicenboim** [comment]
do you have some tool to cut the bdf and store it as bdf again with the same format?
It will be nice to have a very very short file with just some events so that I add it to the unit tests.

**Comment by bnicenboim** [comment]
ok, nevermind, it's just the way BDF codes the triggers. I can test it with any BDF file. I'll solve it tomorrow.

**Comment by livioivil** [comment]
Sorry,
I was not able to make a test file.
Don't stress too much about it.
I'll cope with it anyway

**Comment by bnicenboim** [comment]
ok, it's working in the experimental version of eeguana:
```
remotes::install_github("bnicenboim/eeguana@experimental")
```
I'll do more tests and I'll release a new version

**Comment by livioivil** [comment]
Thank you!
