### ISSUE TITLE
IIR filter error message: Column `iir` doesn't exist.

### ISSUE THREAD

**Issue by stonekate** [bnicenboim/eeguana#152]
---

Hey, I'm trying to use the IIR filter but get the error above, maybe I missed something:

```r
# load data
dat <- read_vhdr("./1.vhdr")

# add channel positions
 channels_tbl(dat) <- select(channels_tbl(dat), .channel) %>%
    left_join(layout_32_1020)
  
  # filter
  datf <- eeg_filt_band_pass(dat, .freq = c(.01, 30), .method = "iir")
```

![image](https://user-images.githubusercontent.com/12735809/107781885-b4017780-6d48-11eb-9200-e2a519e3cf08.png)

**Comment by bnicenboim** [comment]
oh, maybe I didn't update the documentation. It should be `datf <- eeg_filt_band_pass(dat, .freq = c(.01, 30), .config = list(method = "iir"))`

**Comment by stonekate** [comment]
yup that was it!
