### ISSUE TITLE
Make error message for using a pipe instead of a + in a plot function consistent with ggplot?

### ISSUE THREAD

**Issue by stonekate** [bnicenboim/eeguana#161]
Just a suggestion: If I accidentally use %>% in a plot function instead of +, for example:

```r
dat %>%
  filter(.id %in% c(bad-1, bad, bad+1)) %>%
  select(-EOGH, -EOGV) %>%
  plot() %>%
  annotate_events() 
```
it gives the error "No method for merging layer_events into element_line". 

Might be nice if it had the ggplot error "Did you use %>% instead of +?" (but maybe there's some reason not to).

**Comment by bnicenboim** [comment]
Oh, I think that's ggplot's fault... Does it give a message like that when you do %>% to a geom?

**Comment by stonekate** [comment]
ah interesting, no it gives the ggplot error if I do it to a geom. Never
mind then
