### ISSUE TITLE
error message IIR filter

### ISSUE THREAD

**Issue by stonekate** [bnicenboim/eeguana#194]
In both stable and experimental eeguanas I get the following error with the pipeline below, just for one single subject, all other subjects are fine:

```
# Load data
dat <- read_vhdr("./2.vhdr")

# Add channel positions
channels_tbl(dat) <- select(channels_tbl(dat), .channel) %>%
    left_join(layout_32_1020)
  
# IIR filter
datf <- eeg_filt_band_pass(dat, .freq = c(.01, 30), .config = list(method = "iir"))

```

![image](https://user-images.githubusercontent.com/12735809/170950812-3323c664-b77f-4f7d-b6d0-5be38cea21b9.png)

**Comment by bnicenboim** [comment]
just FYI, I'm working on it. I'm changing all the filtering to a newer package, I think I'll manage to finish it next week

**Comment by bnicenboim** [comment]
ok, I think I fixed it. Please check it with the new experimental version.
