### ISSUE TITLE
Error when binding individual eeg_lsts together

### ISSUE THREAD

**Issue by stonekate** [bnicenboim/eeguana#204]
Hi Bruno, I'm having trouble binding specific participants together (I've put the problematic ones in dropbox). I've tried both main and experimental eeguanas. All the others bind fine so I don't think it's a bug, I just don't understand the error messages from data.table. Any ideas?

```
eeg15 <- readRDS("eeg.15.rds")
eeg16 <- readRDS("eeg.16.rds")
eeg17 <- readRDS("eeg.17.rds")
eeg18 <- readRDS("eeg.18.rds")
eeg19 <- readRDS("eeg.19.rds")

bind(eeg15, eeg16) # works fine
bind(eeg16, eeg17) # this and the following get the error message below
bind(eeg16, eeg18) 

```

I don't know what this means :(
![image](https://user-images.githubusercontent.com/12735809/178485254-1a551f15-64f1-4690-8f0d-580b25d969c3.png)

```
# eeg19 has only RM as a reference because LM didn't work (the others are re-referenced to the average of LM/RM) so it gets an extra warning about that, but I think the error is the same as above:
bind(eeg16, eeg19) 
```
![image](https://user-images.githubusercontent.com/12735809/178485824-8092173a-93c4-45b0-8980-d1827b9a0de0.png)

For some more context, I tried this:

```
bind_rows(eeg16$.signal, eeg17$.signal)
```

![image](https://user-images.githubusercontent.com/12735809/178662292-caf694b0-c647-4a48-b329-7f55fba61a55.png)

**Comment by stonekate** [comment]
PS. All of is_channel_dbl() in the signal tables = TRUE

**Comment by bnicenboim** [comment]
the problem is objects saved with different versions of eeguana. Use the latest experimental version and do `as_eeg_lst(eegN)` before you bind them

**Comment by stonekate** [comment]
aah it worked, thank you!
