### ISSUE TITLE
FieldTrip tutorial: Warning message read_vhdr

### ISSUE THREAD

**Issue by auskate** [bnicenboim/eeguana#30]
I get the following warning (Windows) after reading in the example data. It reads in, but maybe not properly because the first plot after 'Pre-processing and re-referencing' looks different to yours (see attached):

Warning message:
In matrix(as.matrix(amps), ncol = n_chan, byrow = multiplexed) :
  data length [71630921] is not a sub-multiple or multiple of the number of rows [1119234]
![plot_filters](https://user-images.githubusercontent.com/12735809/49038789-3b8d5b00-f1be-11e8-97ce-d88ccf13e9fe.PNG)

**Comment by bnicenboim** [comment]
This seems to be a bug in R, but I should throw an error instead of a warning here.
