### ISSUE TITLE
error when merging tibble with eeg_lst

### ISSUE THREAD

**Issue by auskate** [bnicenboim/eeguana#8]
I get the following error when merging my log files with the eeg_lst:

Joining, by = c("recording", "segment")
Error in as_tibble.signal_tbl(data, .name_repair = "check_unique") : 
  unused argument (.name_repair = "check_unique")

Small script attached. Should work with data already in Dropbox/eegble_tests.

[merge_error.txt](https://github.com/bnicenboim/eeguana/files/2571607/merge_error.txt)

**Comment by bnicenboim** [comment]
can you try it now?

**Comment by auskate** [comment]
and I still get the same error :(

**Comment by bnicenboim** [comment]
grrrr, now you should install a new version

**Comment by auskate** [comment]
ok, new version installed. Error is new, but sounds simple...:

Joining, by = c("recording", "segment")
Error: 'semi_join_dt' is not an exported object from 'namespace:dplyr'

**Comment by bnicenboim** [comment]
sorry, I was too cocky. Now it's tested, and it works in my computer, at least. Please check it.

**Comment by auskate** [comment]
yep, works for me too!
